[package]
name = "Grabbit"
version = "0.1.0"
edition = "2024"

[dependencies]

image = "0.25.8"
bytes = "1.10.1"  # to manuplate the monsters with h[w]
flate2 = "1.1.4"
aes-gcm = "0.10.3"
generic-array = "0.14.7"
typenum = "1.19.0"